### ISSUE TITLE
update examples to import from skbeam instead of skxray

### ISSUE THREAD

**Issue by davidslac** [scikit-beam/scikit-beam-examples#49]
I noticed that examples like this

https://github.com/scikit-beam/scikit-beam-examples/blob/master/demos/time_correlation/one-time-correlation.py

import from skxray instead of skbeam

**Comment by ericdill** [comment]
Ah good catch.  Thanks.  I'll get on this right now

**Comment by sameera2004** [comment]
Thanks @davidslac we have to update our old demos

**Comment by davidslac** [comment]
You're welcome, this is David Schneider who works with Chris O Grady

best,

David Schneider
SLAC/LCLS
________________________________________

**Comment by ericdill** [comment]
This was completed in #50.  Thanks for the report @davidslac !
