### ISSUE TITLE
Are the example tif images corrupt?

### ISSUE THREAD

**Issue by chuckie82** [scikit-beam/scikit-beam-examples#61]
Trying to fix this broken powder_calibration:
scikit-beam-examples/broken/powder_calibration/D_estimate_demo.ipynb

Are the example tif images corrupt?

This piece of code fails:
import pims
si_fname = 'Si_STD_d204-00002.tif'
pims.tiff_stack.TiffStack_tifffile(si_fname)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-43-6f3973b4496a> in <module>()
----> 1 pims.tiff_stack.TiffStack_tifffile(si_fname)

/reg/neh/home3/yoon82/sklearn/lib/python2.7/site-packages/pims/tiff_stack.pyc in __init__(self, filename, process_func, dtype, as_grey)
    112                  as_grey=False):
    113         self._filename = filename
--> 114         record = tifffile.TiffFile(filename).series[0]
    115         if hasattr(record, 'pages'):
    116             self._tiff = record.pages

AttributeError: 'NoneType' object has no attribute 'TiffFile'

**Comment by ericdill** [comment]
Do you have `tifffile` installed?

**Comment by ericdill** [comment]
Ah, I see what is happening here.  `pims` gives us a nice shim layer for reading tiff stacks and will use `tifffile`, `libtiff` or `pil`/`pillow` depending on which of these is available.  By directly importing from `pims.tiff_stack.TiffStack_tifffile` we are bypassing this shim layer.  You can take advantage of this shim layer by changing the line

`from pims.tiff_stack import TiffStack_tifffile as TiffStack`

to

`from pims.api import TiffStack`.

Does that fix it?

**Comment by chuckie82** [comment]
Yes, that works. Thanks!

Could you try running scikit-beam-examples/broken/powder_calibration/D_estimate_demo_fix.ipynb?
There's something strange with the estimate_d function, but nbversion should be fixed.

**Comment by ericdill** [comment]
Looking now.  

Please do not push directly to the master branch of scikit-beam/scikit-beam-examples.  Can you use the following workflow instead? Thanks!

- fork this repository into chuckie82/scikit-beam-examples
- work on a feature branch (maybe something like `fix-estimate-d`, but name it however you like!)
- submit a pull request from your `fix-estimate-d` branch on chuckie82/scikit-beam-examples into the master branch of scikit-beam/scikit-beam-examples

**Comment by ericdill** [comment]
> There's something strange with the estimate_d function

Do you mean the ValueError that is being raised from within numpy?

**Comment by ericdill** [comment]
Specifically:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-32-23f8c796d9eb> in <module>()
----> 1 calib_si = estimate_d(si_data[0], si_name, si_wavelength, pixel_size)
      2 print("D: {} ± {}".format(calib_si[0], calib_si[1]))
      3 print("center: {}".format(calib_si[2]))

<ipython-input-3-5285f337cdcd> in estimate_d(img, name, wavelength, pixel_size)
      2     # find the
      3     res = find_ring_center_acorr_1D(img)
----> 4     res2 = refine_center(img, res, pixel_size, 25, 5, thresh=0.1, window_size=5)
      5     bins, sums, counts = img_to_relative_xyi(img, res2, radial_grid)
      6 

/home/edill/miniconda/envs/beam35/lib/python3.5/site-packages/skbeam/core/calibration.py in refine_center(image, calibrated_center, pixel_size, phi_steps, max_peaks, thresh, window_size, nx, min_x, max_x)
    191         mask = (phi <= phi_end) * (phi > phi_start)
    192         out.append(bin_1D(r[mask], I[mask],
--> 193                           nx=nx, min_x=min_x, max_x=max_x))
    194     out = list(out)
    195 

/home/edill/miniconda/envs/beam35/lib/python3.5/site-packages/skbeam/core/utils.py in bin_1D(x, y, nx, min_x, max_x)
    579     # handle default values
    580     if min_x is None:
--> 581         min_x = np.min(x)
    582     if max_x is None:
    583         max_x = np.max(x)

/home/edill/miniconda/envs/beam35/lib/python3.5/site-packages/numpy/core/fromnumeric.py in amin(a, axis, out, keepdims)
   2352     else:
   2353         return _methods._amin(a, axis=axis,
-> 2354                               out=out, keepdims=keepdims)
   2355 
   2356 

/home/edill/miniconda/envs/beam35/lib/python3.5/site-packages/numpy/core/_methods.py in _amin(a, axis, out, keepdims)
     27 
     28 def _amin(a, axis=None, out=None, keepdims=False):
---> 29     return umr_minimum(a, axis, None, out, keepdims)
     30 
     31 def _sum(a, axis=None, dtype=None, out=None, keepdims=False):

ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by chuckie82** [comment]
Sorry about pushing to master... what was I thinking!

estimated_d function fails I think because of this:
res = find_ring_center_acorr_1D(si_data[0])
print res --> (1,0)
I thought this function should return the center positions of the image?

**Comment by ericdill** [comment]
> Sorry about pushing to master... what was I thinking!

No worries :smile_cat: 

`estimate_d` is failing for a couple of reasons.  First is that the TiffStack loader is not loading the image properly.  The `pil` image loader is treating this as a 16 bit signed integer when it should be treated as a 32 bit unsigned int.  So make that change:

`si_data = TiffStack(si_fname, dtype=np.uint32)`

and 

`lab6_data = TiffStack(lab6_fname, dtype=np.uint32)`

You will probably also want to plot the log of the image data since there are dead/saturated pixels in both data sets that will obscure the rings, so those two code blocks should look like:

```python
si_data = TiffStack(si_fname, dtype=np.uint32)
fig, ax = plt.subplots(figsize=(10,10))
ax.imshow(si_data[0],interpolation='none')
```

and

```python
lab6_data = TiffStack(lab6_fname, dtype=np.uint32)
fig, ax = plt.subplots(figsize=(10,10))
ax.imshow(np.log(lab6_data[0]),interpolation='none')
```

(Also, I would advocate for always doing `fig, ax = plt.subplots()` because if you switch from %matplotlib inline to %matplotlib notebook, your notebook will behave **very** differently, as plt.imshow() will keep plotting to the same figure instead of making a new figure each time, but I digress... Back to the matter at hand!)

So if you make those changes, then you should get images that look like this:

si_data:
![download 2](https://cloud.githubusercontent.com/assets/6223243/13760730/f48e6ed2-ea0a-11e5-8444-f7ce3043be79.png)

lab6_data:
![download 3](https://cloud.githubusercontent.com/assets/6223243/13760732/fa471202-ea0a-11e5-86d9-b5a218bc5523.png)

And then executing `calib_si = estimate_d(si_data[0], si_name, si_wavelength, pixel_size)` should produce the following error:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-14-23f8c796d9eb> in <module>()
----> 1 calib_si = estimate_d(si_data[0], si_name, si_wavelength, pixel_size)
      2 print("D: {} ± {}".format(calib_si[0], calib_si[1]))
      3 print("center: {}".format(calib_si[2]))

<ipython-input-3-5285f337cdcd> in estimate_d(img, name, wavelength, pixel_size)
      3     res = find_ring_center_acorr_1D(img)
      4     res2 = refine_center(img, res, pixel_size, 25, 5, thresh=0.1, window_size=5)
----> 5     bins, sums, counts = img_to_relative_xyi(img, res2, radial_grid)
      6 
      7     mask = counts > 10

NameError: name 'img_to_relative_xyi' is not defined
```

Let me do some digging to figure out what happened to that function...  That this function is missing is one of the reasons why this notebook is broken

**Comment by chuckie82** [comment]
It's missing this:
from skbeam.core.utils import img_to_relative_xyi

**Comment by ericdill** [comment]
Oh great, so we just moved that function.  I was worried that we renamed or deleted it or something.

**Comment by chuckie82** [comment]
```
si_data = TiffStack(si_fname,dtype='uint')
img = si_data[0]
res = find_ring_center_acorr_1D(img)
print res --> (1040, 1020)
```

It seems dtype needs to be 'int' (not 'np.uint32' or 'uint') for find_ring_center_acorr_1D and refine_center to output the correct output. Visually, I expected the centre to be roughly (1042.08,1019.63)

```
bins, sums, counts = img_to_relative_xyi(img, res2[0], res2[1], 
                                         pixel_size_x=.2, pixel_size_y=.2)
```

API changed from res2 tuple to res2.x and res2.y

So the code runs without crashing now... but the output still doesn't make sense:
D: nan ± nan
center: (1040.5375337561584, 1020.3334525778171)

Any hunches as to where it may fail?

**Comment by chuckie82** [comment]
```
x,y,I = img_to_relative_xyi(img, res2[0], res2[1], 
                                         pixel_size_x=.2, pixel_size_y=.2)
```
It turns out img_to_relative_xy no longer outputs (bins, sums, counts). New output is (x,y,I)

To get the bins I need, I used this function:
```
d=np.sqrt(x**2+y**2)
edges,val,count = bin_1D(d,I)
```
Not really sure whether this is correct.

Final d_mean is 234.6mm

**Comment by ericdill** [comment]
attn @tacaswell or @sameera2004 do either of you remember what the correct distance is?

**Comment by sameera2004** [comment]
I think this is the same sample 'Si_STD_d204-00002.tif`, 
####################
Si_STD_d204-00002.tif
Si
 wavelength 0.1839

 Calibration Data 
-----------------------
distance to sample
206.625295437mm
 Standard error 
0.0148469111084

 Center of the X-ray rings 

X- co-ordinate 
1026.4785033
Fit2d x co-ordinate 
1021.5214967

Y - co-ordinate
1040.36915868
Fit2d y co-ordinate
1007.63084132
######

**Comment by chuckie82** [comment]
Thanks @sameera2004 for the information.

@ericdill, I think it's fixed now except for the minor issue in the last line, nsls2.calibration.calibration_standards['LaB6']. I don't have nsls2 installed.

Si data results:
D: 206.54687354536938 Â± 0.44676404752969634
center: (1040.5375337561584, 1020.3334525778171)

Lab 6 data results:
D: 493.24928496090615 Â± 0.44625343620719043
center: (1011.735038759629, 1027.5116910034903)

FYI, I was hoping this example would work for LCLS, but the algorithm isn't designed to handle multi-panel detector gaps. Most of the functions in estimate_d will need to handle masks. _This could be a recurring theme._

**Comment by ericdill** [comment]
Thanks for your work on this!

Can you try again with the image dtype being `np.uint32`?  I am reasonably sure that these images should be treated as unsigned, not signed.  

> nsls2.calibration.calibration_standards['LaB6']

Change that to `skbeam.core.constants.calibration_standards['LaB6']`. `nsls2` was the original name of this library, before `scikit-xray` and now `scikit-beam`.

> Most of the functions in estimate_d will need to handle masks. This could be a recurring theme.

Indeed. It seems to be under discussion at scikit-beam/scikit-beam#429

**Comment by chuckie82** [comment]
Thanks! I got rid of nsls2 and changed the magic number to pixel size.

**Comment by chuckie82** [comment]
FYI, reading in tiffs as np.uint32 fails:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-23-46ccc14059fc> in <module>()
----> 1 calib_si = estimate_d(si_data[0].astype(np.uint32), si_name, si_wavelength, pixel_size)
      2 print("D: {} Â± {}".format(calib_si[0], calib_si[1]))
      3 print("center: {}".format(calib_si[2]))

<ipython-input-6-c64a156b11fd> in estimate_d(img, name, wavelength, pixel_size, mask)
      2     # find the center
      3     res = find_ring_center_acorr_1D(img)
----> 4     res2 = refine_center(img, res, pixel_size, 25, 5, thresh=0.1, window_size=5)
      5     x,y,I = img_to_relative_xyi(img, res2[1], res2[0], pixel_size[1], pixel_size[0])
      6     # used to be bins, sums, counts

/reg/neh/home/yoon82/anaconda3/lib/python3.5/site-packages/skbeam/core/calibration.py in refine_center(image, calibrated_center, pixel_size, phi_steps, max_peaks, thresh, window_size, nx, min_x, max_x)
    204         cands = filter_peak_height(avg, cands, thresh*np.max(avg),
    205                                    window=window_size)
--> 206         ring_trace.append(bin_centers[cands[:max_peaks]])
    207 
    208     tr_len = [len(rt) for rt in ring_trace]

IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by ericdill** [comment]
It looks like you are reading in the si_data as an `int` and then casting it to `np.uint32`. Can you try to read it in as a uint32: 

```python
si_data = TiffStack(si_fname, dtype=np.uint32)
```

@sameera2004 do you know how the data should be treated?

**Comment by chuckie82** [comment]
I tried that also... it fails in a similar manner.

**Comment by ericdill** [comment]
Ok well it seems to be working just fine.  Can you move this notebook to scikit-beam-examples/demos/powder_calibration/?  Other than that it LGTM. Thanks for working on this :grinning:

**Comment by chuckie82** [comment]
Thanks for all the help!
I pushed the final version to scikit-beam-examples/demos/powder_calibration on #62.

**Comment by ericdill** [comment]
Awesome thanks. I'm going to close this issue and move the final bits of discussion to #62
